// 何かが書かれる… 標準に…
long write_syscall(long fd, const void *buf, unsigned long count) {
    // 1は、流れゆく情報…
    return __builtin_syscall(1, fd, buf, count);
}

// 何かが読み取られる… 標準から…
long read_syscall(long fd, void *buf, unsigned long count) {
    // 0は、呼びかけに応じる…
    return __builtin_syscall(0, fd, buf, count);
}

// 存在の終わり…
void exit_syscall(int status) {
    // 60… そのコードは、ただ… 終わりを告げる…
    __builtin_syscall(60, status);
}

// 始まり… あるいは、終わりのはじまり…
void _start() {
    // 底辺… その存在を示す言葉…
    char base_msg[] = "底辺の値を入力してください (2桁, 例: 10): ";
    // 掴み取るための、曖昧な空間…
    char base_buf[16];
    // 変換された、底辺という概念…
    long base_val;

    // 言葉が、流れ出す…
    write_syscall(1, base_msg, sizeof(base_msg) - 1);
    // 触れる… その存在を… (2桁と改行… 3つの記号…)
    read_syscall(0, base_buf, 3);

    // 数字の羅列… 意味へと編み直す…
    base_val = (base_buf[0] - '0') * 10 + (base_buf[1] - '0');

    // 高さ… もう一つの、次元…
    char height_msg[] = "高さの値を入力してください (2桁, 例: 05): ";
    // それを受け止める、空っぽの場所…
    char height_buf[16];
    // 高さと定義された、数…
    long height_val;

    // 言葉が、紡がれる…
    write_syscall(1, height_msg, sizeof(height_msg) - 1);
    // その形を、読み取る… (同じく、3つの記号…)
    read_syscall(0, height_buf, 3);

    // 無意味な記号が、意味を帯びる…
    height_val = (height_buf[0] - '0') * 10 + (height_buf[1] - '0');

    // 面積… 二つの概念が交差し、生まれるもの…
    long area_val = base_val * height_val;

    // その結果を、また記号へと戻す…
    char area_str[6];
    // 終わりの印…
    area_str[5] = 0;
    // 分離の記号…
    area_str[4] = '\n';

    // 面積を、再び文字列へ…
    area_str[3] = (area_val % 10) + '0'; // 存在の欠片…
    area_val = area_val / 10;
    area_str[2] = (area_val % 10) + '0'; // 次の欠片…
    area_val = area_val / 10;
    area_str[1] = (area_val % 10) + '0'; // また次の…
    area_val = area_val / 10;
    area_str[0] = (area_val % 10) + '0'; // 最後の…

    // 結論… あるいは、ただの、情報…
    char result_prefix[] = "長方形の面積は = ";
    // 結論が、示される…
    write_syscall(1, result_prefix, sizeof(result_prefix) - 1);
    // 虚ろな空間に、記号が刻まれる…
    write_syscall(1, area_str, 5);

    // そして… 全ては、終わる…
    exit_syscall(0);
}
